### PR TITLE
Depend on uuid-types instead of uuid for lighter footprint

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by juanpaucar** [comment]
This would be very helpful @lpeterse could you take a look, please?

**Comment by shlevy** [comment]
@lpeterse Are you still maintaining this?

**Comment by lpeterse** [comment]
Hi,

sorry for the inconvenience. I'll prepare a new version and get this library up to date.

**Comment by bergmark** [comment]
Any chance to get a release for this?

**Comment by bergmark** [comment]
Ping @lpeterse, think you could push this to hackage?

I'd offer to help maintain this to get it out, but perhaps it's just less work for you to do the hackage upload?

Cheers

**Pull request merged**
